CLI: Choice Class Reference
Choice Class Reference
Choice user interface class.
#include <ui_choice.h>
Public Member Functions
Choice (const int I_DefaultChoice, const tk::Queue< ResourceString > &TK_Choices)
Top execution context constructor.
Choice (ExecutionContext &CLI_ParentContext, const int I_DefaultChoice, const tk::Queue< ResourceString > &TK_Choices)
Child execution context constructor.
virtual ~Choice (void)
Destructor.
const int GetChoice (void) const
Choice retrieval.
const ResourceString GetstrChoice (void) const
Choice retrieval in its string form.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Protected Member Functions
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Detailed Description
Choice user interface class.
Definition at line 43 of file ui_choice.h.
Constructor & Destructor Documentation
Choice::Choice (const int I_DefaultChoice, const tk::Queue< ResourceString > & TK_Choices) [explicit]
Top execution context constructor.
Parameters:
I_DefaultChoice Index in the input queue corresponding to the default answer.
TK_Choices Input choice list.
Definition at line 69 of file ui_choice.cpp.
References Choice().
Referenced by Choice().
Choice::Choice (ExecutionContext & CLI_ParentContext, const int I_DefaultChoice, const tk::Queue< ResourceString > & TK_Choices) [explicit]
Child execution context constructor.
Parameters:
CLI_ParentContext Parent execution context.
I_DefaultChoice Index in the input queue corresponding to the default answer.
TK_Choices Input choice list.
Definition at line 75 of file ui_choice.cpp.
References Choice().
Choice::~Choice (void) [virtual]
Destructor.
Definition at line 81 of file ui_choice.cpp.
Member Function Documentation
const int Choice::GetChoice (void) const
Choice retrieval.
Returns:
Index in the input queue corresponding to the answer entered by the user. -1 if no matching choice found.
Definition at line 85 of file ui_choice.cpp.
References Line::GetLine().
Referenced by GetstrChoice(), YesNo::GetYesNo(), and OnKey().
const ResourceString Choice::GetstrChoice (void) const
Choice retrieval in its string form.
Returns:
String of the choice. Empty string if no matching choice found.
Definition at line 119 of file ui_choice.cpp.
References GetChoice().
Referenced by OnKey().
void Choice::OnKey (const KEY E_KeyCode) [virtual]
Handler called on character input.
Parameters:
E_KeyCode Input key.
Reimplemented from Line.
Reimplemented in YesNo.
Definition at line 142 of file ui_choice.cpp.
References ExecutionContext::Beep(), UI::EndControl(), ENTER, GetChoice(), GetstrChoice(), KEY_DOWN, KEY_UP, NULL_KEY, PAGE_DOWN, PAGE_UP, and Line::SetLine().
void Choice::ResetToDefault (void) [protected, virtual]
Handler called when default value is required to be restored.
Reimplemented from Line.
Definition at line 133 of file ui_choice.cpp.
References ExecutionContext::GetLang(), and Line::SetLine().
The documentation for this class was generated from the following files:
ui_choice.h
ui_choice.cpp