CLI: UI Class Reference
UI Class Reference
Generic user interface class.
#include <ui.h>
Public Member Functions
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Protected Member Functions
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
virtual void Reset (void)=0
Handler called when data reset is required.
virtual void ResetToDefault (void)=0
Handler called when default value is required to be restored.
Detailed Description
Generic user interface class.
Definition at line 60 of file ui.h.
Constructor & Destructor Documentation
UI::UI (void) [explicit, protected]
Top execution context constructor.
Definition at line 39 of file ui.cpp.
UI::UI (ExecutionContext & CLI_ExecutionContext) [explicit, protected]
Child execution context constructor.
Parameters:
CLI_ExecutionContext Parent execution context.
Definition at line 44 of file ui.cpp.
UI::~UI (void) [virtual]
Destructor.
Definition at line 49 of file ui.cpp.
Member Function Documentation
void UI::EndControl (const bool B_ExecResult) [protected]
Method to call by child classes in order to end the control execution.
Parameters:
B_ExecResult Execution result, true for success, false otherwise.
Definition at line 79 of file ui.cpp.
References ExecutionContext::StopExecution().
Referenced by Password::OnKey(), Line::OnKey(), Int::OnKey(), Float::OnKey(), and Choice::OnKey().
const bool UI::GetbExecResult (void) const
Execution result accessor.
Returns:
Execution result: true for a regular output, false for an error or a cancellation.
Definition at line 53 of file ui.cpp.
const bool UI::OnStartExecution (void) [protected, virtual]
Beginning of execution handler.
Returns:
true for success, false otherwise.
Implements ExecutionContext.
Definition at line 58 of file ui.cpp.
References Reset(), and ResetToDefault().
const bool UI::OnStopExecution (void) [protected, virtual]
Execution termination handler.
Returns:
true for success, false otherwise.
Implements ExecutionContext.
Definition at line 67 of file ui.cpp.
References ECHO_STREAM, endl, ExecutionContext::GetStream(), and ResetToDefault().
virtual void UI::Reset (void) [protected, pure virtual]
Handler called when data reset is required.
Implemented in Less, Line, More, and Password.
Referenced by OnStartExecution().
virtual void UI::ResetToDefault (void) [protected, pure virtual]
Handler called when default value is required to be restored.
Implemented in Choice, Float, Int, Less, Line, More, and Password.
Referenced by OnStartExecution(), and OnStopExecution().
The documentation for this class was generated from the following files:
ui.h
ui.cpp