CLI: CmdLineEdition Class Reference
CmdLineEdition Class Reference
Command line edition objet.
#include <command_line_edition.h>
Public Member Functions
CmdLineEdition (const CmdLineEdition &)
Copy constructor.
CmdLineEdition (void)
Default constructor.
virtual ~CmdLineEdition (void)
Destructor.
CmdLineEdition & operator= (const CmdLineEdition &)
Assignment operator.
void Set (const tk::String &TK_Left, const tk::String &TK_Right)
Set the object.
void Reset (void)
Reset the object.
void SetInsertMode (const bool B_InsertMode)
Insert mode setting.
const bool GetInsertMode (void) const
Insert mode retrieval.
void Put (const OutputDevice &CLI_OutputDevice, const char C_Char)
Character addition.
void Put (const OutputDevice &CLI_OutputDevice, const tk::String &TK_String)
String addition.
void CleanAll (const OutputDevice &CLI_OutputDevice)
Line deletion.
void Delete (const OutputDevice &CLI_OutputDevice, const int I_Count)
Character deletion.
void PrintCmdLine (const OutputDevice &CLI_OutputDevice) const
Command line display.
void MoveCursor (const OutputDevice &CLI_OutputDevice, const int I_Count)
Moves the cursor.
void NextLine (const OutputDevice &CLI_OutputDevice)
Moves the cursor to the next line.
void Home (const OutputDevice &CLI_OutputDevice)
Moves the cursor at the beginning of the line.
void End (const OutputDevice &CLI_OutputDevice)
Moves the cursor at the end of the line.
const tk::String GetLine (void) const
Current command line.
const tk::String GetRight (void) const
Right part of the command line accessor.
const tk::String GetLeft (void) const
Left part of the command line accessor.
const tk::String GetNextWord (void) const
Next word retrieval.
const tk::String GetPrevWord (void) const
Previous word retrieval.
Detailed Description
Command line edition objet.
Definition at line 47 of file command_line_edition.h.
Constructor & Destructor Documentation
CmdLineEdition::CmdLineEdition (const CmdLineEdition &)
Copy constructor.
CmdLineEdition::CmdLineEdition (void) [explicit]
Default constructor.
virtual CmdLineEdition::~CmdLineEdition (void) [virtual]
Destructor.
Member Function Documentation
void CmdLineEdition::CleanAll (const OutputDevice & CLI_OutputDevice)
Line deletion.
Parameters:
CLI_OutputDevice Output device.
Referenced by Password::OnKey(), Line::OnKey(), Password::ResetToDefault(), and Line::SetLine().
void CmdLineEdition::Delete (const OutputDevice & CLI_OutputDevice, const int I_Count)
Character deletion.
Note:
If the deletion would move the cursor out of the bounds of the line, the cursor gets stuck either at the beginning (when deleting backward) or at the end (when deleting forward).
Parameters:
CLI_OutputDevice Output device.
I_Count Number of characters to delete. A positive value means deleting characters forward (from the right of the cursor). A negative value means deleting characters backward (from the left of the cursor, ie backspace).
Referenced by Password::OnKey(), and Line::OnKey().
void CmdLineEdition::End (const OutputDevice & CLI_OutputDevice)
Moves the cursor at the end of the line.
Parameters:
CLI_OutputDevice Output device.
Referenced by Password::OnKey(), and Line::OnKey().
const bool CmdLineEdition::GetInsertMode (void) const
Insert mode retrieval.
Returns:
Current insert mode.
Referenced by Password::OnKey(), and Line::OnKey().
const tk::String CmdLineEdition::GetLeft (void) const
Left part of the command line accessor.
Returns:
The left part of the command line.
Referenced by Password::OnKey(), and Line::OnKey().
const tk::String CmdLineEdition::GetLine (void) const
Current command line.
Returns:
The current command line.
Referenced by Line::GetLine(), Password::GetPassword(), Password::OnKey(), and Line::OnKey().
const tk::String CmdLineEdition::GetNextWord (void) const
Next word retrieval.
Returns:
The next word after the cursor.
Note:
A word means until the next blank.
const tk::String CmdLineEdition::GetPrevWord (void) const
Previous word retrieval.
Returns:
The previous word before the cursor.
Note:
A word means until the next blank.
const tk::String CmdLineEdition::GetRight (void) const
Right part of the command line accessor.
Returns:
The right part of the command line.
Referenced by Password::OnKey(), and Line::OnKey().
void CmdLineEdition::Home (const OutputDevice & CLI_OutputDevice)
Moves the cursor at the beginning of the line.
Parameters:
CLI_OutputDevice Output device.
Referenced by Password::OnKey(), and Line::OnKey().
void CmdLineEdition::MoveCursor (const OutputDevice & CLI_OutputDevice, const int I_Count)
Moves the cursor.
Note:
If the call would move the cursor out of the bounds of the line, the cursor gets stuck either at the beginning (when moving backward) or at the end (when moving forward).
Parameters:
CLI_OutputDevice Output device.
I_Count Number of characters to switch. A positive value means moving forward (on the right). A negative value means moving backward (on the left).
Referenced by Password::OnKey(), and Line::OnKey().
void CmdLineEdition::NextLine (const OutputDevice & CLI_OutputDevice)
Moves the cursor to the next line.
Parameters:
CLI_OutputDevice Output device.
Referenced by Password::OnKey(), Line::OnKey(), and Line::SetLine().
CmdLineEdition& CmdLineEdition::operator= (const CmdLineEdition &)
Assignment operator.
Returns:
The CmdLineEdition instance itself.
void CmdLineEdition::PrintCmdLine (const OutputDevice & CLI_OutputDevice) const
Command line display.
Note:
Displays the current command line, positionning the cursor at the correct place.
Parameters:
CLI_OutputDevice Output device.
void CmdLineEdition::Put (const OutputDevice & CLI_OutputDevice, const char C_Char)
Character addition.
Parameters:
CLI_OutputDevice Output device.
C_Char Character to add.
Referenced by Password::OnKey(), Line::OnKey(), and Line::SetLine().
void CmdLineEdition::Put (const OutputDevice & CLI_OutputDevice, const tk::String & TK_String)
String addition.
Parameters:
CLI_OutputDevice Output device.
TK_String String to add.
void CmdLineEdition::Reset (void)
Reset the object.
Note:
Does not print out anything.
Referenced by Password::OnKey(), Password::Reset(), Line::Reset(), and Password::ResetToDefault().
void CmdLineEdition::Set (const tk::String & TK_Left, const tk::String & TK_Right)
Set the object.
Note:
Does not print out anything.
Parameters:
TK_Left Left part of the command line.
TK_Right Right part of the command line.
void CmdLineEdition::SetInsertMode (const bool B_InsertMode)
Insert mode setting.
Note:
Default is on.
Parameters:
B_InsertMode Insert Mode.
Referenced by Password::OnKey(), and Line::OnKey().
The documentation for this class was generated from the following file:
command_line_edition.h