CLI: OutputDevice::ScreenInfo Class Reference
OutputDevice::ScreenInfo Class Reference
Screen information.
#include <io_device.h>
Public Types
enum { UNKNOWN = -1, DEFAULT_WIDTH = 80, DEFAULT_HEIGHT = 20 }
ScreenInfo regular values.
Public Member Functions
ScreenInfo (const int I_Width, const int I_Height, const bool B_TrueCls, const bool B_WrapLines)
Constructor.
ScreenInfo (const ScreenInfo &CLI_Info)
Copy constructor.
~ScreenInfo (void)
Destructor.
ScreenInfo & operator= (const ScreenInfo &CLI_ScreenInfo)
Assignment operator.
const int GetWidth (void) const
Screen width accessor.
const unsigned int GetSafeWidth (void) const
Safe screen width accessor.
const int GetHeight (void) const
Screen height accessor.
const unsigned int GetSafeHeight (void) const
Safe screen height accessor.
const bool GetbTrueCls (void) const
True CleanScreen() characteristic accessor.
const bool GetbWrapLines (void) const
Line wrapping characteristic accessor.
Public Attributes
enum
OutputDevice::ScreenInfo:: { ... } _RegularValues
ScreenInfo regular values.
Detailed Description
Screen information.
Definition at line 267 of file io_device.h.
Member Enumeration Documentation
anonymous enum
ScreenInfo regular values.
Returns:
N/A (doxygen warning)
Enumerator:
UNKNOWN
Unknown value constant for either width or height.
DEFAULT_WIDTH
Default width constant.
DEFAULT_HEIGHT
Default height constant.
Definition at line 272 of file io_device.h.
Constructor & Destructor Documentation
OutputDevice::ScreenInfo::ScreenInfo (const int I_Width, const int I_Height, const bool B_TrueCls, const bool B_WrapLines) [inline, explicit]
Constructor.
Parameters:
I_Width Width of screen. Can be UNKNOWN.
I_Height Height of screen. Can be UNKNOWN.
B_TrueCls True when an efficient CleanScreen() operation is implemented.
B_WrapLines True when the line automatically goes down when the cursor reached the right end of the screen.
Definition at line 284 of file io_device.h.
OutputDevice::ScreenInfo::ScreenInfo (const ScreenInfo & CLI_Info) [inline]
Copy constructor.
Parameters:
CLI_Info Dimension object to copy.
Definition at line 294 of file io_device.h.
OutputDevice::ScreenInfo::~ScreenInfo (void) [inline]
Destructor.
Definition at line 301 of file io_device.h.
Member Function Documentation
const bool OutputDevice::ScreenInfo::GetbTrueCls (void) const [inline]
True CleanScreen() characteristic accessor.
Returns:
True CleanScreen() characteristic.
Definition at line 330 of file io_device.h.
const bool OutputDevice::ScreenInfo::GetbWrapLines (void) const [inline]
Line wrapping characteristic accessor.
Returns:
Line wrapping characteristic.
Definition at line 333 of file io_device.h.
const int OutputDevice::ScreenInfo::GetHeight (void) const [inline]
Screen height accessor.
Returns:
Screen height if known, UNKNOWN otherwise.
Definition at line 324 of file io_device.h.
References UNKNOWN.
const unsigned int OutputDevice::ScreenInfo::GetSafeHeight (void) const [inline]
Safe screen height accessor.
Returns:
Screen height if known, default value otherwise.
Definition at line 327 of file io_device.h.
References DEFAULT_HEIGHT.
Referenced by More::OnKey(), More::ResetToDefault(), and Less::ResetToDefault().
const unsigned int OutputDevice::ScreenInfo::GetSafeWidth (void) const [inline]
Safe screen width accessor.
Returns:
Screen width if known, default value otherwise.
Definition at line 321 of file io_device.h.
References DEFAULT_WIDTH.
Referenced by Text::LineDown(), Text::LineUp(), More::OnKey(), and More::ResetToDefault().
const int OutputDevice::ScreenInfo::GetWidth (void) const [inline]
Screen width accessor.
Returns:
Screen width if known, UNKNOWN otherwise.
Definition at line 318 of file io_device.h.
References UNKNOWN.
ScreenInfo& OutputDevice::ScreenInfo::operator= (const ScreenInfo & CLI_ScreenInfo) [inline]
Assignment operator.
Returns:
Same ScreenInfo instance reference.
Parameters:
CLI_ScreenInfo Screen information to copy.
Definition at line 305 of file io_device.h.
Member Data Documentation
enum { ... } OutputDevice::ScreenInfo::_RegularValues
ScreenInfo regular values.
Returns:
N/A (doxygen warning)
The documentation for this class was generated from the following file:
io_device.h