CLI: More Class Reference
More Class Reference
Simple line user interface object.
#include <ui_more.h>
Public Member Functions
More (const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength)
Top execution context constructor.
More (ExecutionContext &CLI_ParentContext, const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength)
Child execution context constructor.
virtual ~More (void)
Destructor.
const OutputDevice & GetText (void)
Text member accessor.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Protected Member Functions
virtual void Reset (void)
Handler called when data reset is required.
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Detailed Description
Simple line user interface object.
Definition at line 52 of file ui_more.h.
Constructor & Destructor Documentation
More::More (const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength) [explicit]
Top execution context constructor.
Parameters:
UI_MaxLines Maximum number of lines
UI_MaxLineLength Maximum length of lines
Definition at line 42 of file ui_more.cpp.
Referenced by More().
More::More (ExecutionContext & CLI_ParentContext, const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength) [explicit]
Child execution context constructor.
Parameters:
CLI_ParentContext Parent execution context.
UI_MaxLines Maximum number of lines
UI_MaxLineLength Maximum length of lines
Definition at line 49 of file ui_more.cpp.
References More().
More::~More (void) [virtual]
Destructor.
Definition at line 56 of file ui_more.cpp.
Member Function Documentation
const OutputDevice & More::GetText (void)
Text member accessor.
Returns:
Text member reference.
Definition at line 67 of file ui_more.cpp.
void More::OnKey (const KEY E_KeyCode) [virtual]
Handler called on character input.
Parameters:
E_KeyCode Input key.
Implements ExecutionContext.
Definition at line 96 of file ui_more.cpp.
References ExecutionContext::Beep(), BREAK, CLI_ASSERT, ENTER, ESCAPE, OutputDevice::ScreenInfo::GetSafeHeight(), OutputDevice::ScreenInfo::GetSafeWidth(), OutputDevice::GetScreenInfo(), ExecutionContext::GetStream(), StringDevice::GetString(), KEY_DOWN, KEY_END, Text::LineDown(), LOGOUT, NULL_KEY, OUTPUT_STREAM, PAGE_DOWN, Text::PageDown(), and SPACE.
void More::Reset (void) [protected, virtual]
Handler called when data reset is required.
Implements UI.
Definition at line 72 of file ui_more.cpp.
void More::ResetToDefault (void) [protected, virtual]
Handler called when default value is required to be restored.
Implements UI.
Definition at line 77 of file ui_more.cpp.
References Text::Begin(), CLI_ASSERT, OutputDevice::ScreenInfo::GetSafeHeight(), OutputDevice::ScreenInfo::GetSafeWidth(), OutputDevice::GetScreenInfo(), ExecutionContext::GetStream(), StringDevice::GetString(), OUTPUT_STREAM, and Text::PrintPage().
The documentation for this class was generated from the following files:
ui_more.h
ui_more.cpp