CLI: Int Class Reference
Int Class Reference
Integer user interface object.
#include <ui_int.h>
Public Member Functions
Int (const int I_DefaultValue, const int I_MinValue, const int I_MaxValue)
Top execution context constructor.
Int (ExecutionContext &CLI_ParentContext, const int I_DefaultValue, const int I_MinValue, const int I_MaxValue)
Child execution context constructor.
virtual ~Int (void)
Destructor.
const int GetInt (void) const
Integer retrieval.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Protected Member Functions
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Detailed Description
Integer user interface object.
Definition at line 43 of file ui_int.h.
Constructor & Destructor Documentation
Int::Int (const int I_DefaultValue, const int I_MinValue, const int I_MaxValue) [explicit]
Top execution context constructor.
Parameters:
I_DefaultValue Default value.
I_MinValue Minimum value.
I_MaxValue Maximum value.
Definition at line 54 of file ui_int.cpp.
References Int().
Referenced by Int().
Int::Int (ExecutionContext & CLI_ParentContext, const int I_DefaultValue, const int I_MinValue, const int I_MaxValue) [explicit]
Child execution context constructor.
Parameters:
CLI_ParentContext Parent execution context.
I_DefaultValue Default value.
I_MinValue Minimum value.
I_MaxValue Maximum value.
Definition at line 60 of file ui_int.cpp.
References Int().
Int::~Int (void) [virtual]
Destructor.
Definition at line 66 of file ui_int.cpp.
Member Function Documentation
const int Int::GetInt (void) const
Integer retrieval.
Returns:
Integer value entered by the user.
Definition at line 70 of file ui_int.cpp.
References Line::GetLine(), and ParamInt::SetstrValue().
Referenced by OnKey().
void Int::OnKey (const KEY E_KeyCode) [virtual]
Handler called on character input.
Parameters:
E_KeyCode Input key.
Reimplemented from Line.
Definition at line 86 of file ui_int.cpp.
References ExecutionContext::Beep(), UI::EndControl(), ENTER, GetInt(), KEY_DOWN, KEY_UP, NULL_KEY, PAGE_DOWN, PAGE_UP, and Line::SetLine().
void Int::ResetToDefault (void) [protected, virtual]
Handler called when default value is required to be restored.
Reimplemented from Line.
Definition at line 81 of file ui_int.cpp.
The documentation for this class was generated from the following files:
ui_int.h
ui_int.cpp